# Generated by Django 5.2.8 on 2025-11-12 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompressionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('quality', models.IntegerField(default=50)),
                ('down', models.IntegerField(default=2)),
                ('original_size', models.IntegerField()),
                ('compressed_size', models.IntegerField()),
                ('payload_size', models.IntegerField()),
                ('base_size', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('psnr', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
