# Generated by Django 5.2.8 on 2025-11-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressionrecord',
            name='compression_ratio',
            field=models.FloatField(default=0.0, help_text='Percentage of size saved'),
        ),
        migrations.AddField(
            model_name='compressionrecord',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
