# Generated by Django 5.2.8 on 2025-11-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0002_compressionrecord_compression_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compressionrecord',
            name='psnr',
        ),
    ]
