# Generated by Django 5.2.8 on 2025-11-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compressor', '0003_remove_compressionrecord_psnr'),
    ]

    operations = [
        migrations.AddField(
            model_name='compressionrecord',
            name='output_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
